Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/jammy64"

  # FORCE single SSH key for all VMs
  config.ssh.insert_key = false

  # Default provider settings (applies to all unless overridden)
  config.vm.provider "virtualbox" do |vb|
    vb.memory = 2048   # default: 2 GB
    vb.cpus = 2
  end

  # Disable synced folder (recommended for k8s)
  config.vm.synced_folder ".", "/vagrant", disabled: true

  # ======================
  # Control Plane
  # ======================
  config.vm.define "control-plane" do |master|
    master.vm.hostname = "k8s-master"

    # Override hardware ONLY for control plane
    master.vm.provider "virtualbox" do |vb|
      vb.memory = 8192   # 8 GB RAM
      vb.cpus = 2
    end

    master.vm.network "private_network",
      ip: "192.168.56.10",
      auto_config: true
  end

  # ======================
  # Worker Node 01
  # ======================
  config.vm.define "worker-node-01" do |node|
    node.vm.hostname = "k8s-node-01"

    node.vm.network "private_network",
      ip: "192.168.56.11",
      auto_config: true
  end

  # ======================
  # Worker Node 02
  # ======================
  config.vm.define "worker-node-02" do |node|
    node.vm.hostname = "k8s-node-02"

    node.vm.network "private_network",
      ip: "192.168.56.12",
      auto_config: true
  end
end
